# Generated by Django 3.2.3 on 2021-05-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.CharField(max_length=255, unique=True)),
                ('art_content', models.CharField(max_length=1023)),
                ('art_author', models.CharField(max_length=255)),
                ('art_time', models.DateField(auto_now=True)),
                ('art_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('art_title', models.CharField(max_length=255)),
                ('commentor', models.CharField(max_length=255)),
                ('commentwho', models.IntegerField(default=0)),
                ('comment_content', models.CharField(max_length=127)),
                ('comment_time', models.DateField(auto_now=True)),
            ],
        ),
    ]
