# Generated by Django 3.2.3 on 2021-05-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210526_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='art_title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
