# Generated by Django 3.2.3 on 2021-05-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210526_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='art_title',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
